apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: felipechamone
  name: project2-pv2-felipechamone
  labels:
    type: local
spec:
  storageClassName: default-storage-class-felipechamone
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: /home/felipechamone/project2-pv2