apiVersion: apps/v1
kind: Deployment
metadata:
  name: playlist-recommender-deployment
  labels:
    app: cadar-playlist-recommender
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cadar-playlist-recommender
  template:
    metadata:
      labels:
        app: cadar-playlist-recommender
    spec:
      containers:
      - name: backend
        image: radac98/playlist-backend:1.0.0
        ports:
        - containerPort: 52019
        env:
        - name: PORT
          value: "52019"
        volumeMounts:
        - name: data-volume
          mountPath: /app/data
      - name: frontend
        image: radac98/playlist-frontend:1.0.0
        ports:
        - containerPort: 80
        env:
        - name: BACKEND_PORT
          value: "52019"       # Ensure it matches the backend container port
        volumeMounts:
        - name: data-volume
          mountPath: /app/data
      - name: ml-training
        image: radac98/playlist-ml-training:1.0.0
        ports:
        - containerPort: 52020
        env:
        - name: PORT
          value: "52020"
        - name: UPLOAD_FOLDER
          value: "/app/data/uploads"
        volumeMounts:
        - name: data-volume
          mountPath: /app/data
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: cadar-spotify-pvc