apiVersion: apps/v1
kind: Deployment
metadata:
  name: felipechamone-project2-deployment
  labels:
    app: felipechamone-project2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: felipechamone-project2
  template:
    metadata:
      labels:
        app: felipechamone-project2
    spec:
      containers:
      - name: backend
        image: quay.io/radac98/playlist-backend:1.0.1
        ports:
        - containerPort: 30746
        env:
        - name: PORT
          value: "52019"
        volumeMounts:
        - name: data-volume
          mountPath: /app/data
      - name: frontend
        image: quay.io/radac98/playlist-frontend:1.0.1
        ports:
        - containerPort: 52019
        env:
        - name: BACKEND_PORT
          value: "52019"       # Ensure it matches the backend container port
        volumeMounts:
        - name: data-volume
          mountPath: /app/data
      - name: ml-training
        image: quay.io/radac98/playlist-ml-training:1.0.1
        ports:
        - containerPort: 30747
        env:
        - name: PORT
          value: "52020"
        - name: UPLOAD_FOLDER
          value: "/app/data/uploads"
        volumeMounts:
        - name: data-volume
          mountPath: /app/data
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: project2-pvc2-felipechamone