apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cadar-spotify-pvc
spec:
  selector:
    matchLabels:
      namespace: felipechamone
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 300Mi                  # Matches the PV size