apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: project2-pvc2-felipechamone
spec:
  storageClassName: default-storage-class-felipechamone
  selector:
    matchLabels:
      namespace: felipechamone
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 300Mi                  # Matches the PV size