apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: project2-pvc2-felipechamone
spec:
  selector:
    matchLabels:
      namespace: felipechamone
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi                  # Matches the PV size