apiVersion: v1
kind: Service
metadata:
  name: playlist-recommender-service
spec:
  selector:
    app: cadar-playlist-recommender # Matches pods with this label
  ports:
  - name: frontend-port    # Name for the frontend port
    protocol: TCP
    port: 80               # Frontend port
    targetPort: 80         # Matches the frontend container
  - name: backend-port     # Name for the backend/ML training port
    protocol: TCP
    port: 52019            # Backend/ML port
    targetPort: 52019      # Matches the backend or ML container
  - name: training-port    # Name for the training website port
    protocol: TCP
    port: 52020            # Training website port
    targetPort: 52020      # Matches the training container
  type: LoadBalancer       # Use with cloud or load balancer support