apiVersion: v1
kind: Service
metadata:
  name: playlist-recommender-service
  namespace: cadar
spec:
  selector:
    app: playlist-recommender
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: backend
      protocol: TCP
      port: 30502
      targetPort: 30502
